stages:
- package
package:
  stage: package
  tags:
  - whtf_ai
  script:
  # - yarn
  # - yarn build
  # - rm -rf /datastorage/webserver/files/webserver/web/html/pjfy*
  - \cp -r ./dist/* /datastorage/webserver/files/webserver/web/html/pjfy
